name: matrix-appservice-slack
base: core18
version: git 
summary: Matrix appservice bridge for Slack rooms
description: |
  This bridge allows you to connect Slack channels to Matrix rooms.

grade: stable 
confinement: strict 

apps:
  matrix-appservice-slack: 
    command: 'bin/matrix-appservice-slack-wrapper'
    plugs: [network-bind, network]
    daemon: simple
parts:
  nodejs-lts:
    plugin: nil
    override-build: |
      NODE_VERSION=12.13.0
      case $SNAPCRAFT_ARCH_TRIPLET in
      x86_64-*)
        NODE_ARCH="x64"
        ;;
      aarch64-*)
        NODE_ARCH="arm64"
        ;;
      arm-linux-gnueabihf)
        NODE_ARCH="armv7l"
        ;;
      powerpc64le-*)
        NODE_ARCH="ppc64le"
        ;;
      s390x-*)
        NODE_ARCH="s390x"
        ;;
      esac
      echo "Fetching node $NODE_VERSION for $NODE_ARCH"
      wget "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-$NODE_ARCH.tar.xz" -O /tmp/nodejs.tar.xz
      tar Jxf /tmp/nodejs.tar.xz -C $SNAPCRAFT_PART_INSTALL/ --strip 1
      rm $SNAPCRAFT_PART_INSTALL/README.md
      rm $SNAPCRAFT_PART_INSTALL/CHANGELOG.md
      rm $SNAPCRAFT_PART_INSTALL/LICENSE
      snapcraftctl build
  matrix-appservice-slack:
    source: .
    plugin: dump
    build-packages:
      - make
      - gcc
      - g++
      - binutils
      - python
      - git
    override-build: |
      npm install
      snapcraftctl build
    organize:
      snap/local/wrapper: bin/matrix-appservice-slack-wrapper
    after: [nodejs-lts]
