# Based on https://github.com/matrix-org/dendrite/blob/master/.github/workflows/docker-hub.yml

name: "Docker Hub - Latest"

on:
  push:

env:
  DOCKER_NAMESPACE: matrixdotorg
  # Explicity not building arm64 images to reduce build times
  PLATFORMS: linux/amd64
  PLATFORMS_DEVELOP: linux/arm64,linux/amd64
  # Only push if this is develop, otherwise we just want to build
  PUSH: ${{ github.ref == 'refs/heads/develop' }}

jobs:
  docker-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
  
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up QEMU
        if: ${{ env.PUSH }}
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        if: ${{ env.PUSH }}
        uses: docker/setup-buildx-action@v1      

      - name: Build image
        uses: docker/build-push-action@v2
        if: github.ref != 'refs/heads/develop'
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: ${{ env.PUSH }}
          tags: |
            ${{ env.DOCKER_NAMESPACE }}/matrix-appservice-slack:latest

      - name: Build and push image 
        uses: docker/build-push-action@v2
        if: github.ref == 'refs/heads/develop'
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ env.PLATFORMS_DEVELOP }}
          push: ${{ env.PUSH }}
          tags: |
            ${{ env.DOCKER_NAMESPACE }}/matrix-appservice-slack:latest
