name: Newsfile

on:
  pull_request:
  workflow_dispatch:

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: # Needed for comparison
          fetch-depth: 0
      - uses: actions/setup-python@v2
      - run: pip install towncrier==22.8.0
      - name: ":newspaper: Newsfile"
        run: ./scripts/check-newsfragment
        env:
          PULL_REQUEST_NUMBER: ${{ github.event.number }}
